public class TelecareJSONWrapperClass {

    public class ContactWrapper{
        public String Email { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Gender { get; set; }
        public String NPINumber { get; set; }
        public String MobilePhone { get; set; }
        public String AddressBlock { get; set; }
        public Boolean IsActive { get; set; }
        public DateTime ContractDate { get; set; }
    }
    

}